title: Cloud & DevOps Knowledge Base
description: Practical notes on AWS, Terraform, Docker, Kubernetes & Automation
theme: null  # Remove or comment this
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme  # Add if missing
  - jekyll-feed
  - jekyll-seo-tag


markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Ram Dhamdar
