title: Cloud & DevOps Knowledge Base
description: Practical notes on AWS, Terraform, Docker, Kubernetes & Automation

url: "https://RamDhamdar2313.github.io"
baseurl: "/knowledge-base"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

permalink: /blogs/:title/

author:
  name: Ram Dhamdar
